### PR TITLE
Add creation & modification time

### PR DESCRIPTION
**Pull request by Luigi600**
Adds two functions to read the creation date and modification date of an entry.

Due to the time specification of C must still be converted into ms (see new constant)...

### CODE REVIEW

**Comment by ofk** [comment]
Thank you for adding this feature!
Just one small request for a correction.
`ArchiveReaderEntry` serves as a wrapper for `ArchiveReader`.
Therefore, I would like the return values of both `ArchiveReaderEntry#getCreationTime` and `ArchiveReader#getCreationTime` to be the same.
Could you please make the necessary changes so that `ArchiveReader#getCreationTime` and `getModificationTime` return time in milliseconds?

**Comment by Luigi600** [comment]
I did it.

**Comment by ofk** [comment]
Thank you. I will fix the test.

**Comment by ofk** [comment]
While writing tests and investigating, I noticed that `getCreationTime` seems to always return 0.
Since I'm not very familiar with this, could you please provide guidance on the correct usage of `archive_entry_ctime`?
If it remains unclear, I'm considering removing `getCreationTime` as it appears to be meaningless.

**Comment by ofk** [comment]
In most cases, archive files do not have ctime, so it was found that `archive_entry_ctime` returns 0. However, since this function exists in libarchive, I have decided to keep `getCreationTime`. Thank you for your contribution!

**Comment by Luigi600** [comment]
Just for completeness: The modification date as well as the creation date and other dates are optional (see https://manpages.debian.org/jessie/libarchive-dev/archive_entry_time.3.en.html - no idea why Debian has a better "API documentation" than the GitHub page of the libarchive). It can be considered to implement the `is_set` method, but I personally would not omit it in any case!

**Pull request merged**
